server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.231:8660/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
spring:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      jdbcUrl: jdbc:mysql://192.168.1.230:3306/wh_admin_tenant?useUnicode=true&nullCatalogMeansCurrent=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
    ################Redis
  application:
    name: tenant-service
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  #mapper-locations: classpath*:mapper/**/*.xml  #配置映射xml地址


